// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: av-cli.proto

package avcli

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Designation string `protobuf:"bytes,2,opt,name=designation,proto3" json:"designation,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_av_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_av_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_av_cli_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ID) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

type IDResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *IDResult) Reset() {
	*x = IDResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_av_cli_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResult) ProtoMessage() {}

func (x *IDResult) ProtoReflect() protoreflect.Message {
	mi := &file_av_cli_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResult.ProtoReflect.Descriptor instead.
func (*IDResult) Descriptor() ([]byte, []int) {
	return file_av_cli_proto_rawDescGZIP(), []int{1}
}

func (x *IDResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IDResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetLogLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port  int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Level int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_av_cli_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_cli_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_av_cli_proto_rawDescGZIP(), []int{2}
}

func (x *SetLogLevelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetLogLevelRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SetLogLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type ScreenshotResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photo []byte `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (x *ScreenshotResult) Reset() {
	*x = ScreenshotResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_av_cli_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenshotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResult) ProtoMessage() {}

func (x *ScreenshotResult) ProtoReflect() protoreflect.Message {
	mi := &file_av_cli_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResult.ProtoReflect.Descriptor instead.
func (*ScreenshotResult) Descriptor() ([]byte, []int) {
	return file_av_cli_proto_rawDescGZIP(), []int{3}
}

func (x *ScreenshotResult) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type CopyRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src            string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	SrcDesignation string `protobuf:"bytes,2,opt,name=srcDesignation,proto3" json:"srcDesignation,omitempty"`
	Dst            string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	DstDesignation string `protobuf:"bytes,4,opt,name=dstDesignation,proto3" json:"dstDesignation,omitempty"`
}

func (x *CopyRoomRequest) Reset() {
	*x = CopyRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_av_cli_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRoomRequest) ProtoMessage() {}

func (x *CopyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_cli_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRoomRequest.ProtoReflect.Descriptor instead.
func (*CopyRoomRequest) Descriptor() ([]byte, []int) {
	return file_av_cli_proto_rawDescGZIP(), []int{4}
}

func (x *CopyRoomRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyRoomRequest) GetSrcDesignation() string {
	if x != nil {
		return x.SrcDesignation
	}
	return ""
}

func (x *CopyRoomRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *CopyRoomRequest) GetDstDesignation() string {
	if x != nil {
		return x.DstDesignation
	}
	return ""
}

var File_av_cli_proto protoreflect.FileDescriptor

var file_av_cli_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x76, 0x2d, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x61, 0x76, 0x63, 0x6c, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x36, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x08, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x12,
	0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x28, 0x0a, 0x10,
	0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x70, 0x79, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x26, 0x0a, 0x0e,
	0x73, 0x72, 0x63, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x72, 0x63, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x73, 0x74, 0x44, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x64, 0x73, 0x74, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x9e,
	0x03, 0x0a, 0x05, 0x41, 0x76, 0x43, 0x6c, 0x69, 0x12, 0x26, 0x0a, 0x04, 0x53, 0x77, 0x61, 0x62,
	0x12, 0x09, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x61, 0x76,
	0x63, 0x6c, 0x69, 0x2e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x27, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x09, 0x2e, 0x61, 0x76, 0x63, 0x6c,
	0x69, 0x2e, 0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x32, 0x0a, 0x0a, 0x53, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x09, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e,
	0x49, 0x44, 0x1a, 0x17, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x08, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x2e, 0x61, 0x76, 0x63, 0x6c,
	0x69, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x07, 0x46,
	0x69, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x09, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49,
	0x44, 0x1a, 0x0f, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x26, 0x0a, 0x04, 0x53, 0x69, 0x6e, 0x6b, 0x12, 0x09,
	0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x61, 0x76, 0x63, 0x6c,
	0x69, 0x2e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b,
	0x0a, 0x14, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e,
	0x67, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x09, 0x2e, 0x61, 0x76, 0x63, 0x6c, 0x69, 0x2e, 0x49,
	0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x2e, 0x61, 0x76, 0x63,
	0x6c, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_av_cli_proto_rawDescOnce sync.Once
	file_av_cli_proto_rawDescData = file_av_cli_proto_rawDesc
)

func file_av_cli_proto_rawDescGZIP() []byte {
	file_av_cli_proto_rawDescOnce.Do(func() {
		file_av_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_av_cli_proto_rawDescData)
	})
	return file_av_cli_proto_rawDescData
}

var file_av_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_av_cli_proto_goTypes = []interface{}{
	(*ID)(nil),                 // 0: avcli.ID
	(*IDResult)(nil),           // 1: avcli.IDResult
	(*SetLogLevelRequest)(nil), // 2: avcli.SetLogLevelRequest
	(*ScreenshotResult)(nil),   // 3: avcli.ScreenshotResult
	(*CopyRoomRequest)(nil),    // 4: avcli.CopyRoomRequest
	(*empty.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_av_cli_proto_depIdxs = []int32{
	0, // 0: avcli.AvCli.Swab:input_type -> avcli.ID
	0, // 1: avcli.AvCli.Float:input_type -> avcli.ID
	0, // 2: avcli.AvCli.Screenshot:input_type -> avcli.ID
	4, // 3: avcli.AvCli.CopyRoom:input_type -> avcli.CopyRoomRequest
	0, // 4: avcli.AvCli.FixTime:input_type -> avcli.ID
	0, // 5: avcli.AvCli.Sink:input_type -> avcli.ID
	0, // 6: avcli.AvCli.CloseMonitoringIssue:input_type -> avcli.ID
	2, // 7: avcli.AvCli.SetLogLevel:input_type -> avcli.SetLogLevelRequest
	1, // 8: avcli.AvCli.Swab:output_type -> avcli.IDResult
	1, // 9: avcli.AvCli.Float:output_type -> avcli.IDResult
	3, // 10: avcli.AvCli.Screenshot:output_type -> avcli.ScreenshotResult
	5, // 11: avcli.AvCli.CopyRoom:output_type -> google.protobuf.Empty
	1, // 12: avcli.AvCli.FixTime:output_type -> avcli.IDResult
	1, // 13: avcli.AvCli.Sink:output_type -> avcli.IDResult
	5, // 14: avcli.AvCli.CloseMonitoringIssue:output_type -> google.protobuf.Empty
	5, // 15: avcli.AvCli.SetLogLevel:output_type -> google.protobuf.Empty
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_av_cli_proto_init() }
func file_av_cli_proto_init() {
	if File_av_cli_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_av_cli_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_av_cli_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_av_cli_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLogLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_av_cli_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenshotResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_av_cli_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_av_cli_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_av_cli_proto_goTypes,
		DependencyIndexes: file_av_cli_proto_depIdxs,
		MessageInfos:      file_av_cli_proto_msgTypes,
	}.Build()
	File_av_cli_proto = out.File
	file_av_cli_proto_rawDesc = nil
	file_av_cli_proto_goTypes = nil
	file_av_cli_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AvCliClient is the client API for AvCli service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AvCliClient interface {
	Swab(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_SwabClient, error)
	Float(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_FloatClient, error)
	Screenshot(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ScreenshotResult, error)
	CopyRoom(ctx context.Context, in *CopyRoomRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FixTime(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_FixTimeClient, error)
	Sink(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_SinkClient, error)
	CloseMonitoringIssue(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error)
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type avCliClient struct {
	cc grpc.ClientConnInterface
}

func NewAvCliClient(cc grpc.ClientConnInterface) AvCliClient {
	return &avCliClient{cc}
}

func (c *avCliClient) Swab(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_SwabClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AvCli_serviceDesc.Streams[0], "/avcli.AvCli/Swab", opts...)
	if err != nil {
		return nil, err
	}
	x := &avCliSwabClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AvCli_SwabClient interface {
	Recv() (*IDResult, error)
	grpc.ClientStream
}

type avCliSwabClient struct {
	grpc.ClientStream
}

func (x *avCliSwabClient) Recv() (*IDResult, error) {
	m := new(IDResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *avCliClient) Float(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_FloatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AvCli_serviceDesc.Streams[1], "/avcli.AvCli/Float", opts...)
	if err != nil {
		return nil, err
	}
	x := &avCliFloatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AvCli_FloatClient interface {
	Recv() (*IDResult, error)
	grpc.ClientStream
}

type avCliFloatClient struct {
	grpc.ClientStream
}

func (x *avCliFloatClient) Recv() (*IDResult, error) {
	m := new(IDResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *avCliClient) Screenshot(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ScreenshotResult, error) {
	out := new(ScreenshotResult)
	err := c.cc.Invoke(ctx, "/avcli.AvCli/Screenshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avCliClient) CopyRoom(ctx context.Context, in *CopyRoomRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/avcli.AvCli/CopyRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avCliClient) FixTime(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_FixTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AvCli_serviceDesc.Streams[2], "/avcli.AvCli/FixTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &avCliFixTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AvCli_FixTimeClient interface {
	Recv() (*IDResult, error)
	grpc.ClientStream
}

type avCliFixTimeClient struct {
	grpc.ClientStream
}

func (x *avCliFixTimeClient) Recv() (*IDResult, error) {
	m := new(IDResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *avCliClient) Sink(ctx context.Context, in *ID, opts ...grpc.CallOption) (AvCli_SinkClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AvCli_serviceDesc.Streams[3], "/avcli.AvCli/Sink", opts...)
	if err != nil {
		return nil, err
	}
	x := &avCliSinkClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AvCli_SinkClient interface {
	Recv() (*IDResult, error)
	grpc.ClientStream
}

type avCliSinkClient struct {
	grpc.ClientStream
}

func (x *avCliSinkClient) Recv() (*IDResult, error) {
	m := new(IDResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *avCliClient) CloseMonitoringIssue(ctx context.Context, in *ID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/avcli.AvCli/CloseMonitoringIssue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avCliClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/avcli.AvCli/SetLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvCliServer is the server API for AvCli service.
type AvCliServer interface {
	Swab(*ID, AvCli_SwabServer) error
	Float(*ID, AvCli_FloatServer) error
	Screenshot(context.Context, *ID) (*ScreenshotResult, error)
	CopyRoom(context.Context, *CopyRoomRequest) (*empty.Empty, error)
	FixTime(*ID, AvCli_FixTimeServer) error
	Sink(*ID, AvCli_SinkServer) error
	CloseMonitoringIssue(context.Context, *ID) (*empty.Empty, error)
	SetLogLevel(context.Context, *SetLogLevelRequest) (*empty.Empty, error)
}

// UnimplementedAvCliServer can be embedded to have forward compatible implementations.
type UnimplementedAvCliServer struct {
}

func (*UnimplementedAvCliServer) Swab(*ID, AvCli_SwabServer) error {
	return status.Errorf(codes.Unimplemented, "method Swab not implemented")
}
func (*UnimplementedAvCliServer) Float(*ID, AvCli_FloatServer) error {
	return status.Errorf(codes.Unimplemented, "method Float not implemented")
}
func (*UnimplementedAvCliServer) Screenshot(context.Context, *ID) (*ScreenshotResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Screenshot not implemented")
}
func (*UnimplementedAvCliServer) CopyRoom(context.Context, *CopyRoomRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyRoom not implemented")
}
func (*UnimplementedAvCliServer) FixTime(*ID, AvCli_FixTimeServer) error {
	return status.Errorf(codes.Unimplemented, "method FixTime not implemented")
}
func (*UnimplementedAvCliServer) Sink(*ID, AvCli_SinkServer) error {
	return status.Errorf(codes.Unimplemented, "method Sink not implemented")
}
func (*UnimplementedAvCliServer) CloseMonitoringIssue(context.Context, *ID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseMonitoringIssue not implemented")
}
func (*UnimplementedAvCliServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogLevel not implemented")
}

func RegisterAvCliServer(s *grpc.Server, srv AvCliServer) {
	s.RegisterService(&_AvCli_serviceDesc, srv)
}

func _AvCli_Swab_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvCliServer).Swab(m, &avCliSwabServer{stream})
}

type AvCli_SwabServer interface {
	Send(*IDResult) error
	grpc.ServerStream
}

type avCliSwabServer struct {
	grpc.ServerStream
}

func (x *avCliSwabServer) Send(m *IDResult) error {
	return x.ServerStream.SendMsg(m)
}

func _AvCli_Float_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvCliServer).Float(m, &avCliFloatServer{stream})
}

type AvCli_FloatServer interface {
	Send(*IDResult) error
	grpc.ServerStream
}

type avCliFloatServer struct {
	grpc.ServerStream
}

func (x *avCliFloatServer) Send(m *IDResult) error {
	return x.ServerStream.SendMsg(m)
}

func _AvCli_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvCliServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avcli.AvCli/Screenshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvCliServer).Screenshot(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvCli_CopyRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvCliServer).CopyRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avcli.AvCli/CopyRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvCliServer).CopyRoom(ctx, req.(*CopyRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvCli_FixTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvCliServer).FixTime(m, &avCliFixTimeServer{stream})
}

type AvCli_FixTimeServer interface {
	Send(*IDResult) error
	grpc.ServerStream
}

type avCliFixTimeServer struct {
	grpc.ServerStream
}

func (x *avCliFixTimeServer) Send(m *IDResult) error {
	return x.ServerStream.SendMsg(m)
}

func _AvCli_Sink_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvCliServer).Sink(m, &avCliSinkServer{stream})
}

type AvCli_SinkServer interface {
	Send(*IDResult) error
	grpc.ServerStream
}

type avCliSinkServer struct {
	grpc.ServerStream
}

func (x *avCliSinkServer) Send(m *IDResult) error {
	return x.ServerStream.SendMsg(m)
}

func _AvCli_CloseMonitoringIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvCliServer).CloseMonitoringIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avcli.AvCli/CloseMonitoringIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvCliServer).CloseMonitoringIssue(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvCli_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvCliServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avcli.AvCli/SetLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvCliServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AvCli_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avcli.AvCli",
	HandlerType: (*AvCliServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screenshot",
			Handler:    _AvCli_Screenshot_Handler,
		},
		{
			MethodName: "CopyRoom",
			Handler:    _AvCli_CopyRoom_Handler,
		},
		{
			MethodName: "CloseMonitoringIssue",
			Handler:    _AvCli_CloseMonitoringIssue_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _AvCli_SetLogLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Swab",
			Handler:       _AvCli_Swab_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Float",
			Handler:       _AvCli_Float_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FixTime",
			Handler:       _AvCli_FixTime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sink",
			Handler:       _AvCli_Sink_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "av-cli.proto",
}
